services:
  mower:
    image: arkmower/arknights-mower:latest
    container_name: arknights-mower
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      # ⚠️ 重要设置 - Mower 配置项，将会强制覆盖已有配置文件，请务必在此配置
      # ⚠️ Mower 访问令牌，若留空或保持默认则每回随机生成，可以查看启动日志获取
      - MOWER_TOKEN=PLEASE_CHANGE_ME
      # ⚠️ Mower 监听端口，需与下方端口映射一致
      - MOWER_PORT=58000
      # 非 Mower 配置项
      # 可选：设置 HTTP 代理，用于从海外源下载 MAA 等资源
      # - HTTP_PROXY=http://localhost:7890
    ports:
      - "58000:58000"
    volumes:
      # ⚠️ 重要设置 - Mower 所需的数据文件夹，存放配置文件、日志等，请务必挂载以防数据丢失
      # ⚠️ MAA 文件夹
      - ./maa:/MAA
      # ⚠️ Mower 数据文件夹
      - ./mower-data:/mower-data
    
